### ISSUE TITLE
Maby it need to indicate that a field is a primary key

### ISSUE THREAD

**Issue by heibor** [synw/sqlcool#10]
When I create the DB scheme, sometimes I need to indicate that a field is a primary key, is it possible ?

**Comment by synw** [comment]
For simplicity the primary key is automatically managed by the schema: an id column is created for each table, which is the standard way. This is not configurable

**Comment by heibor** [comment]
Thank you.

**Comment by 32mandev** [comment]
It would be nice if we had the possibility to change the name of the primary key column (id), or even to setup a set of several columns as primary keys.

**Comment by synw** [comment]
This will not be implemented because too specific: it is not worth supporting the extra complexity this feature would introduce in the code for very limited benefits: in such a case just write your own create table query by hand
