### ISSUE TITLE
How to do coverage report for sqlcool unit test

### ISSUE THREAD

**Issue by flutteradv** [synw/sqlcool#15]
I can run sqlcool tests using flutter run "test file path" but I need to include test in coverage report. How should I do that. any code samples appreciated

**Comment by synw** [comment]
To run the tests with coverage use:

```bash
pub run test_coverage --no-badge && genhtml -o coverage coverage/lcov.info
```
The coverage then can be viewed at `coverage/index.html`

**Comment by flutteradv** [comment]
when I run the above command I got following error:
`Could not find a file named "pubspec.yaml" in "/Users/MoNa/.pub-cache/hosted/pub.dartlang.org/file-5.0.8+1".`
also I can run for regulat POJO unit tests using

> flutter test --coverage 

for sqlCool unit tests I have to run on device by 
`flutter run test file
`
so there is no way to include in coverage report. I saw there is coverage report in this repo how that is done?
>

**Comment by synw** [comment]
Yes use:
```bash
flutter test --coverage && genhtml coverage/lcov.info -o coverage/output
```
This is how the coverage report is done

**Comment by flutteradv** [comment]
but that gives following error:
`MissingPluginException(No implementation found for method getApplicationDocumentsDirectory on channel plugins.flutter.io/path_provider)`

**Comment by synw** [comment]
Does this happen when you run `flutter test` from the main directory of the Sqlcool package ot when running your own tests? 

The tests mock the app directory so this is not supposed to happen: https://github.com/synw/sqlcool/blob/master/test/base.dart#L15 : the `Db.ìnit` method in the tests must always be run with the `absolutePath: true` parameter to be able to run on a computer and avoid path provider incompatibilities

**Comment by flutteradv** [comment]
I face the error when running my own tests and here is my test code:
```
Map item = {
    '@token': mockToken,
    'refreshToken': mockRefreshToken,
    '@time_bubble': '1y',
    '@time_list': '1M',
    "@first_time": 'yes'
  };
  AppModel model = AppModel();
  SharedPreferences prefs = await getReloadedSharedPreferencesInstance();
  Db sql;
  ObjectDB odb;
  sql = Db();
  await sql.init(
      path: "db.sqlite", verbose: true, queries: kAppDatabaseTableQueries);
  model.db = sql;
  model.odb = odb;
  model.init(item, prefs);
test("changeTimeFilter test", () async {
      UserModel userModel = UserModel(
          id: "79cf2048cae6f287b7b8ca271a567129",
          email: "anon@newsconsole.com",
          title: "anon",
          alias: "AN",
          self:
              "https: //newsconsole.com/test/api/napi2/nodes/79cf2048cae6f287b7b8ca271a567129");
      model.user = userModel;
      await model.changeTimeFilter({"value": "6M", "type": "list"});
      List<Map<String, dynamic>> users_meta =
          await model.db.query("SELECT * FROM users_meta");
      expect(users_meta[0], {
        "id": 1,
        "user_id": "79cf2048cae6f287b7b8ca271a567129",
        "meta_key": "time_filter",
        "meta_value": "6M",
        'updated': null
      });
      model.timeFilterController.stream.last.then((timeMap) {
        expect(timeMap, {"value": "6M", "type": "list"});
      });
    });

    test("setTabsAllowed test", () async {
      UserModel userModel = UserModel(
          id: "79cf2048cae6f287b7b8ca271a567129",
          email: "anon@newsconsole.com",
          title: "anon",
          alias: "AN",
          self:
              "https: //newsconsole.com/test/api/napi2/nodes/79cf2048cae6f287b7b8ca271a567129");
      model.user = userModel;
      await model.setTabsAllowed(10);
      List<Map<String, dynamic>> users_meta =
          await model.db.query("SELECT * FROM users_meta");
      expect(users_meta.last["meta_value"], '10');
      model.tabsController.stream.last.then((maxTab) {
        expect(maxTab, 10);
      });
    });
```
How should I mock sqlcool update and query calls for unit tests

**Comment by synw** [comment]
As the running database in tests is fake you must mock the query results: check `channel.setMockMethodCallHandler` in https://github.com/synw/sqlcool/blob/master/test/base.dart for how to proceed

Mock everything that is platform specific: I see that you have a reference to shared preferences for example, not sure that this one can run on desktop

**Comment by flutteradv** [comment]
I have following code to mock prefrences:
```
Future<SharedPreferences> getReloadedSharedPreferencesInstance() async {
  SharedPreferences.setMockInitialValues({});
  return await SharedPreferences.getInstance()
    ..reload();
}

```
Should I change the sqflite package to sqlcool in following code:
`const MethodChannel channel = MethodChannel('com.tekartik.sqflite');
`

**Comment by synw** [comment]
> Should I change the sqflite package to sqlcool in following code:
> const MethodChannel channel = MethodChannel('com.tekartik.sqflite'); 

No,keep it: the method channels belong to Sqflite

**Comment by flutteradv** [comment]
Thanks a lot. I thought I should test db on device which is not possible to include in coverage report
