### ISSUE TITLE
Update pair string problem.

### ISSUE THREAD

**Issue by ilshookim** [synw/sqlcool#16]
Hello,

sqlcool-4.1.0 has some SQL update problem.
insert query is not correct.

so you need to change the code:
https://github.com/synw/sqlcool/blob/master/lib/src/database.dart
458 line: 
pairs = "$pairs, "; 
===>
pairs = ", ";

Thank you.

**Comment by synw** [comment]
Fixed in 4.1.1

@ilshookim thank you for the report. It is strange that the tests did not catch this: I'll investigate to try to make better tests. 

I was thinking about extracting the query construction logic to a dedicated function, it should be more testable and clean
