### ISSUE TITLE
SelectBloc Reactive doesn't trigger when not current screen

### ISSUE THREAD

**Issue by KsaRedFx** [synw/sqlcool#2]
If I have SelectBloc set to be reactive, and use a StreamBuilder to build my home page, 
Then update the table it is watching while on a different page, it fails to update the original home page.

I tried also calling setState() via listening to the _changefeed, however that doesn't work either. 

Is this a limitation of sqlcool/SelectBloc/StreamBuilder and something I should solve myself?

**Comment by synw** [comment]
There is no known limitation of this kind in Sqlcool. Try to check where the error comes from by using the `verbose` parameter on `SelectBloc` and on your update query. Verify that the update query runs, then verify that the change reaches the select bloc: it will output info with the verbosity on. If it is the case then for some reason the `StreamBuilder` does not rebuild.

Try to perform the steps above and if it does not help please provide some code to reproduce the problem.

**Comment by KsaRedFx** [comment]
I have been running it in verbose mode, 
What I see is several alerts that the database changed, but only from `_changefeed`

I never see SelectBloc do another `SELECT * FROM <table>` or anything similar. 
I'm not even certain the verbose on the SelectBloc works. 

I will update this in a bit with an example of what I'm doing.
It's mostly HomePage SelectBlock -> Sub-view -> New insert in DB -> Back key to HomePage -> No Update

**Comment by synw** [comment]
> I'm not even certain the verbose on the SelectBloc works.

It does, passing the `verbose` parameter to `db.select`. Maybe your `SelectBloc` has been disposed in the process, so that it does not listen to the changefeed anymore.

**Comment by KsaRedFx** [comment]
Maybe that's the case, however I'm unsure how to fix it or why changefeed itself continues to update and announce what is going on.

**Comment by synw** [comment]
Post some code, we'll check

**Comment by KsaRedFx** [comment]
I wrote some code to match, but my new app has pulled in the latest sqlcool.

To meet your latest version I'll have to refactor it all... And I'm not sure how at the moment.

**Comment by synw** [comment]
If you are upgrading to 2.0.0+ there are not many changes: see the [changelog](https://pub.dartlang.org/packages/sqlcool#-changelog-tab-): basically no more default `Db` instance, the `database` param is required for `SelectBloc` and the `changeType` parameter of the changefeed has been renamed to `type`, that's all for the breaking change and the refactor should only take a few minutes, no big deal. For demo code check the example.

**Comment by KsaRedFx** [comment]
I was having a pretty bad time of refactoring to v2 of sqlcool, and I eventually gave up and rolled back to 1.2.0 which made an even worse mess.

In the process of trying to do so, I figured out why SelectBloc wasn't updating; 
The thing I'm doing isn't getting put in the _changefeed properly, just everything around it.

**Comment by synw** [comment]
Good that you sorted this out. If you encounter any other problem feel free to open an issue

**Comment by KsaRedFx** [comment]
Thanks for your time/patience.
