### ISSUE TITLE
Problem with StreamBuilder

### ISSUE THREAD

**Issue by ederluca** [synw/sqlcool#20]
Good Morning

Guys I am in need of help, first I would like to thank you for creating a fantastic plugin that sqlcool helped me a lot, however I am setting up a chat screen using sqlcool + dashchat where I create my block using sqlcool I pass to my streambuilder and consequently for dashchat, the first time the data is displayed on the screen perfectly.

However I use Firebase Messanging for push I intercept the onmessage event in Firebase Messaging and insert it into my database using sqlcool, this works perfectly but the stream created does not update. I already tried to put a break point in some places and unfortunately the screen is not updated anyone would know how to tell me how to proceed to resolve this.

Just in advance I got sqlcool using the same feature for a simpler notification screen and it worked normally but I can't update it

**Comment by synw** [comment]
Did you set `reactive = true` on your select bloc? Maybe I should set this one to `true` by default

**Comment by ederluca** [comment]
Thanks for answering I actually discovered the problem at a certain point in the insert, a field that was passing was a string and the field that I was going to receive was whole, generating the problem.
