### ISSUE TITLE
How to Relation many to one in sqlcool?

### ISSUE THREAD

**Issue by jasteeman** [synw/sqlcool#23]
Hi. I want to make a one-to-many relationship using sqlcool. I have a class model of orders and products. But I don't know how to generate those relationships in order. Then, when I insert from the order, the products are automatically saved and generated

**Comment by synw** [comment]
This is a sql problem: you need an intermediary table between order and product, like order_product that will store ordered items datapoints with a foreign key to order and one to product, so this is easy to query. Check [this answer](https://stackoverflow.com/questions/53091688/modeling-product-orders-in-django/53091887#53091887): it's for Django but it explains well the modeling logic 

> when I insert from the order, the products are automatically saved and generated

I don't understand this: when you order some products they already exist: why do you need to mutate the products on save order?
