### ISSUE TITLE
Built-in parsing system

### ISSUE THREAD

**Issue by mzakizadeh** [synw/sqlcool#24]
Currently we are engaging with `Map<String, String>` for both `insert` and `select` (even that it returns a `Map<String, dynamic>`) queries. It's better to create some kind of built-in system to parse data to `String` and back from `String` based on column type.

**Comment by synw** [comment]
Could you provide a pseudo code example of what you suggest? I don't really see what you mean in details

**Comment by synw** [comment]
I still don't know what you mean but as it is related to types you can check #26 that presents the new type safe api to see what you think of this approach
