### ISSUE TITLE
question about database version 

### ISSUE THREAD

**Issue by wjjiang917** [synw/sqlcool#31]
How to insert a new column to exist table?
We can update the database **version** within sqflite, but how to do within sqlcool?

> this._db = await openDatabase(dbpath, version: 1,
>             onCreate: (Database _sqfliteDb, int version) async {
>           await _initQueries(schema, queries, _sqfliteDb, verbose);
>         }, onOpen: (Database _sqfliteDb) async {
>           // run create queries for file copied from an asset
>           if (fromAsset != null && checkCreateQueries) {
>             if (schema != null || queries.isNotEmpty) {
>               await _initQueries(schema, queries, _sqfliteDb, verbose);
>             }
>           }
>         });
>

**Comment by synw** [comment]
The database migrations are not supported in Sqlcool
