### ISSUE TITLE
Getting query error in logcat after DB init called , using v5.1.1

### ISSUE THREAD

**Issue by rakeshparveen5** [synw/sqlcool#35]
D/Sqflite (22844): [1,Sqflite(1100)] CREATE TABLE IF NOT EXISTS tunes (
D/Sqflite (22844): id INTEGER PRIMARY KEY,
D/Sqflite (22844): tuneId VARCHAR NOT NULL,
D/Sqflite (22844): artist TEXT NOT NULL,
D/Sqflite (22844): track TEXT NOT NULL,
D/Sqflite (22844): bpm VARCHAR,
D/Sqflite (22844): key VARCHAR,
D/Sqflite (22844): deleted BOOLEAN DEFAULT false,
D/Sqflite (22844): verified BOOLEAN DEFAULT false,
D/Sqflite (22844): verified_id TEXT NOT NULL DEFAULT ,
D/Sqflite (22844): source INTEGER NOT NULL,
D/Sqflite (22844): createdAt INTEGER NOT NULL,
D/Sqflite (22844): updatedAt INTEGER,
D/Sqflite (22844): album TEXT,
D/Sqflite (22844): comment TEXT,
D/Sqflite (22844): genre TEXT,
D/Sqflite (22844): time TEXT,
D/Sqflite (22844): rating TEXT,
D/Sqflite (22844): dateAdded TEXT
D/Sqflite (22844): )
E/SQLiteLog(22844): (1) near ",": syntax error
D/Sqflite (22844): [1,Sqflite(1100)] ROLLBACK
I/flutter (22844): error DatabaseException(near ",": syntax error (code 1 SQLITE_ERROR): , while compiling: CREATE TABLE IF NOT EXISTS tunes (
I/flutter (22844): id INTEGER PRIMARY KEY,
I/flutter (22844): tuneId VARCHAR NOT NULL,
I/flutter (22844): artist TEXT NOT NULL,
I/flutter (22844): track TEXT NOT NULL,
I/flutter (22844): bpm VARCHAR,
I/flutter (22844): key VARCHAR,
I/flutter (22844): deleted BOOLEAN DEFAULT false,
I/flutter (22844): verified BOOLEAN DEFAULT false,
I/flutter (22844): verified_id TEXT NOT NULL DEFAULT ,
I/flutter (22844): source INTEGER NOT NULL,
I/flutter (22844): createdAt INTEGER NOT NULL,
I/flutter (22844): updatedAt INTEGER,
I/flutter (22844): album TEXT,
I/flutter (22844): comment TEXT,
I/flutter (22844): genre TEXT,
I/flutter (22844): time TEXT,
I/flutter (22844): rating TEXT,
I/flutter (22844): dateAdded TEXT
I/flutter (22844): )) sql 'CREATE TABLE IF NOT EXISTS tunes (
I/flutter (22844): id INTEGER PRIMARY KEY,
I/flutter (22844): tuneId VARCHAR NOT NULL,
I/flutter (22844): artist TEXT NOT NULL,
I/flutter (22844): track TEXT NOT NULL,
I/flutter (22844): bpm VARCHAR,
I/flutter (22844): key VARCHAR,
I/flutter (22844): deleted BOOLEAN DEFAULT false,
I/flutter (22844): verified BOOLEAN DEFAULT false,
I/flutter (22844): verified_id TEXT NOT NULL DEFAULT ,
I/flutter (22844): source INTEGER NOT NULL,
I/flutter (22844): createdAt INTEGER NOT NULL,
I/flutter (22844): updatedAt INTEGER,
I/flutter (22844): album TEXT,
I/flutter (22844): comment TEXT,
I/flutter (22844): genre TEXT,
I/flutter (22844): time TEXT,
I/flutter (22844): rating TEXT,
I/flutter (22844): dateAdded TEXT
I/flutter (22844): )' args []} during open, closing...
D/Sqflite (22844): [1,main(2)] closing 1 /data/user/0/com.myapp/app_flutter/myapp.sqlite
D/Sqflite (22844): [1,Sqflite(1100)] closing database Thread[Sqflite,5,main]
D/Sqflite (22844): [1,Sqflite(1100)] stopping threadThread[Sqflite,5,main]
I/flutter (22844): Closure: () => String from Function 'toString':.
V/FA      (22844): Inactivity, disconnecting from the service

**Comment by synw** [comment]
This looks like a schema error: `verified_id TEXT NOT NULL DEFAULT ,`: this one has no default. Can you provide some code to reproduce this error?

**Comment by rakeshparveen5** [comment]
I checked out the code @synw , yes there I was passing in defaultValue as empty string for the verified_id column. That was causing this exception , as I removed the defaultValue = "" for  verified_id column, everything works fine now.

Thanks for you help @synw 👍
