### ISSUE TITLE
dart:ffi

### ISSUE THREAD

**Issue by ghost** [synw/sqlcool#4]
The Dart FFI feature is now available.
This allows you to call c code direct in flutter without having to use Method Channels.
Hence its MUCH faster when you can talk directly to the c code.

https://github.com/flutter/flutter/issues/7053

https://github.com/dart-lang/sdk/blob/master/samples/ffi/sqlite/docs/sqlite-tutorial.md

**Comment by synw** [comment]
This is relevant at the Sqflite level, which manages the connection to the database with method channels. This module is higher level and will not implement this.
