### ISSUE TITLE
Backup database

### ISSUE THREAD

**Issue by hirenm1990** [synw/sqlcool#7]
I want to offer database backup functionality, in which user can either download DB file or send it via email.

What I have tried is,

```
Db db = Db();
var bytes = await db.file.readAsBytes();
print(bytes.length); // it prints: 4096

WcFlutterShare.share(
        sharePopupTitle: 'Take Backup',
        fileName: 'db.bkup',
        mimeType: 'application/x-sqlite3',
        bytesOfFile: bytes);
```

Here I am using third party library for sharing. Here, I can successfully send db.bkup file to email. But, when I open this file in SqliteBrowser, I can't see any table & it's just empty database.

**Comment by synw** [comment]
Hi. I'm currently afk for a couple of days and can not test your code for the moment. What I use to backup my databases is this: https://github.com/synw/dataview : this is for dev and for users I have another project where you can export your database to local storage: https://github.com/synw/dbswitch . Maybe checking the code there can help. I'll investigate this more when I'll be back to my computer

**Comment by synw** [comment]
>  I can't see any table & it's just empty database

In your code the database is not initialized so it is normal that you get an empty database file. You must run the `init` function to create the tables.

**Comment by hirenm1990** [comment]
Hey synw, thanks for replying.
I have used init() function in my main.dart file & in application data is also storing, as when I restart the application, data is there. I will now try https://github.com/synw/dataview

**Comment by synw** [comment]
I tried with this code:
```
await db.onReady;
final bytes = await db.file.readAsBytes();
final path = db.file.parent.path + "/db_copy.sqlite";
final newFile = File(path).writeAsBytes(bytes);
```

It works fine: I can see the tables in the copied file with Sqlitebrowser. Please double check your code: the error does not seem to come from this library

**Comment by hirenm1990** [comment]
Thanks, now it's working. I was missing db.onReady part :+1:
