### ISSUE TITLE
Support change feed across isolates

### ISSUE THREAD

**Issue by ened** [synw/sqlcool#8]
A quick skim on the source code shows the `.changefeed` property works well on a single instance of the plugin (within the same isolate).

Can this be made to work with background processing, so that a worker process (e.g. started on Android in a service / work manager / separate engine) could signal database changes?

**Comment by synw** [comment]
Hi. Sorry for the late response. Unfortunately it is not possible to run the database in an isolate: the plugins do not work in isolates and the method channels would not be found. 

> started on Android in a service / work manager / separate engine

What is your idea/use case? I tried to run the database in an isolate with no success but maybe you have other plans to try?

**Comment by synw** [comment]
This does not seem to be doable for now, closing
