### ISSUE TITLE
Is it possible to provide a hasField method for DbTable ?

### ISSUE THREAD

**Issue by heibor** [synw/sqlcool#9]
Sometimes, we need to test whether a field is existed in a table, is it possible to provide a `hasField` method in DbTable ?

**Comment by synw** [comment]
It's possible yes, it will probably be named `hasColumn` in respect of the internal semantics. I will implement a getter. For now you can loop on the `columns` property of the schema to do your checks

**Comment by heibor** [comment]
I see, thank you.
